### ISSUE TITLE
Fix intermittent CI timeout failures

### ISSUE THREAD

**Issue by cprice404** [momentohq/client-sdk-python#158]
When PRs are opened against the python SDK right now, and the python version number test matrix begins to execute, some subset of the jobs fail with DEADLINE_EXCEEDED timeouts and need to be re-run.

I haven't investigated too deeply but the failures I've seen often look like they are happening on tests that have a timeout of 60s, and the service is healthy, so this seems like it must be some kind of resource contention issue in the github environment.  We need to either add more debug logging so that we can figure out what the root cause is, or we need to re-work the test configuration so that the jobs run serially instead of in parallel if it is a resource contention issue.

Not really sure yet what the best fix is going to be but we need to get these to a state where there aren't so many transient failures that require retries.

**Comment by cprice404** [comment]
@malandis figured this out - it's something that changed when github cut over their `ubuntu-latest` from Ubuntu 20 to 22.  We haven't been able to repro on our own Ubuntu 22 instances so we believe the problem is specific to github.  Resolution for now:

* @malandis already changed our build back to the old version of ubuntu for now, so things are working again.
* We will file an issue with github to solicit their reaction, and see how that goes, so that in the long term we can hopefully get unblocked to upgrade to 22.

@malandis do you want to add a link from this ticket to the one that you opened with GH?  and then we can close this out.

**Comment by malandis** [comment]
https://github.com/actions/runner-images/issues/6981
