### ISSUE TITLE
Fix strings in Example code

### ISSUE THREAD

**Issue by gautamomento** [momentohq/client-sdk-python#32]
Example code should be using [f-strings](https://docs.python.org/3/tutorial/inputoutput.html#tut-f-strings) instread of concatenating strings with `+`.  Not a huge deal, just makes us look like we know what modern idiomatic python looks like.  e.g.:
    - Instead of: `print('Look up resulted in a : ' + str(get_resp.result()))`
    - should be: `print(f'Look up resulted in a {get_resp.result()}')`

**Comment by malandis** [comment]
Example code is up to date.
