### ISSUE TITLE
Exception on cache_client.get(cache_name, key) for non-scaler type values.

### ISSUE THREAD

**Issue by ash-ishh** [momentohq/client-sdk-python#338]
Scaler type values are being returned as expected.
But for non-scaler type values below exception is being thrown on get call.

```
momento.errors.exceptions.FailedPreconditionException:
FailedPreconditionException(
    message='internal service error',
    error_code=<MomentoErrorCode.FAILED_PRECONDITION_ERROR: (14,)>,
    transport_details=MomentoErrorTransportDetails(
        grpc=MomentoGrpcErrorDetails(
            code=<StatusCode.FAILED_PRECONDITION: (9, 'failed precondition')>,
            details='internal service error', metadata=None
        )
    ),
    message_wrapper="System is not in a state required for the operation's execution")
```

Momento SDK Verion
```
momento==1.5.0
momento-wire-types==0.64.1
```

Python Version - `Python 3.9.16`

**Comment by malandis** [comment]
@ash-ishh if I understand correctly, you are calling `set` on a scalar valued key and then `get` on the same key. You say this works.

Then you store a non-scalar key, for example by calling `dictionary_set_fields`, correct? If so, to retrieve a collection -valued key, you need to call the corresponding `fetch` method. In this case it would be `dictiionary_fetch`. Hence the error for wrong type.

Let me know if this answers your question.

**Comment by ash-ishh** [comment]
Thanks, `dictionary_set_fields` and `dictionary_fetch`  are working.

**Comment by malandis** [comment]
Good to hear that. I regret the indirect error message. We will improve that.
