### ISSUE TITLE
Add helpful toString() for Response Objects

### ISSUE THREAD

**Issue by danielamiao** [momentohq/client-sdk-python#36]
Right now I see `<momento.cache_operation_responses.CreateCacheResponse object at 0x1014d3430>`

**Comment by danielamiao** [comment]
Got user feedback as well: 

"I expect __repr__ methods to be defined in the classes [here](https://github.com/momentohq/client-sdk-python/blob/main/src/momento/cache_operation_types.py). For example, CacheGetResponse should render the status (hit/miss) and value (if there is one). Without the repr methods it's difficult to introspect the objects interactively."

**Comment by malandis** [comment]
Response objects are now dataclasses which include appropriate `__str__` and `__repr__` implementations.
