### ISSUE TITLE
Python vector index client remaining tasks

### ISSUE THREAD

**Issue by malandis** [momentohq/client-sdk-python#366]
- [x] Ensure integration tests pass against alpha locally
- [x] Ensure integration tests pass against alpha in CI. You may need to add the `TEST_VECTOR_INDEX_NAME` variable to job environment
- [x] Audit the error messages. For each operation, test error conditions and ensure the error message is correct, human readable, and does not include extraneous details. They should also be helpful and, if possible, suggest a fix.
- [x] Add integration tests to test bad auth tokens (see commented out tests in the `test_control_async`)
- [x] Add integration tests to test adding vectors to an index where the input vector dimension does not match the index number of dimensions
- [x] Add integration tests to test searching with a query vector where the query vector dimension does not match the index number.
- [x] Audit documentation

**Comment by pratik151192** [comment]
All issues have been addressed under https://github.com/momentohq/client-sdk-python/pull/358/
