### ISSUE TITLE
Async client tests do not run on python 3.7.

### ISSUE THREAD

**Issue by kvcache** [momentohq/client-sdk-python#67]
```
test_set_with_null_key_throws_exception (tests.test_momento_async.TestMomentoAsync) ... /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/unittest/case.py:628: RuntimeWarning: coroutine 'TestMomentoAsync.test_set_with_null_key_throws_exception' was never awaited
```

The test methods' coroutines are instantiated without actually driving them. Here is an example of one way to drive a coroutine to completion to satisfy the requirement that it must have been completed (i.e., it is not necessary to use the keyword `await`)

```
>>> async def foo():
...  pass
... 
>>> a=foo()
>>> del(a)
<stdin>:1: RuntimeWarning: coroutine 'foo' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
>>> a=foo()
>>> a.send(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
StopIteration
>>> del(a)
>>> 
```

**Comment by danielamiao** [comment]
Can also see multiple of these warnings in our tests, they don't break tests since they are just warnings:
https://github.com/momentohq/client-sdk-python/runs/5209240328?check_suite_focus=true

**Comment by malandis** [comment]
Tests now use pytest and the appropriate async plugins. These warnings no longer appear.
